- hosts: consul
  sudo: yes

  vars:
    consul_version: 0.4.1
    consul_datacenter: test
    consul_bind_address: "{{ ansible_eth1.ipv4.address }}"
    consul_node_name: "{{ ansible_eth1.ipv4.address }}"
    consul_servers: ['192.168.10.11']

    consul_client_address: "0.0.0.0"

  roles:
    - role: consul
