---
galaxy_info:
  author: Matthew Finlayson
  description: Installs and configures consul
  company: Jive Software
  platforms:
    - name: Ubuntu
      versions:
        - All
  categories:
    - system
